create extension if not exists "pgcrypto";

create table if not exists public.assistants (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  name text not null,
  business_name text,
  description text,
  template_id bigint,
  config jsonb default '{}'::jsonb,
  is_active boolean default true,
  total_messages bigint default 0,
  total_leads bigint default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  assistant_id bigint references public.assistants(id) on delete cascade,
  visitor_id text,
  user_email text,
  assistant_name text,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  assistant_id bigint references public.assistants(id) on delete set null,
  name text,
  email text,
  phone text,
  source text,
  status text default 'new',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  lead_id bigint references public.leads(id) on delete set null,
  assistant_id bigint references public.assistants(id) on delete set null,
  title text,
  scheduled_at timestamptz not null,
  status text default 'scheduled',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  plan text default 'free',
  status text default 'active',
  stripe_customer_id text,
  stripe_subscription_id text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.knowledge (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  assistant_id bigint references public.assistants(id) on delete cascade,
  title text,
  content text,
  type text default 'manual',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.assistants enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.leads enable row level security;
alter table public.appointments enable row level security;
alter table public.subscriptions enable row level security;
alter table public.knowledge enable row level security;

create policy "Users manage own assistants" on public.assistants
  for all using (auth.uid() = user_id);
create policy "Users manage own conversations" on public.conversations
  for all using (auth.uid() = user_id);
create policy "Users manage own messages" on public.messages
  for all using (exists (select 1 from public.conversations c where c.id = messages.conversation_id and c.user_id = auth.uid()));
create policy "Users manage own leads" on public.leads
  for all using (auth.uid() = user_id);
create policy "Users manage own appointments" on public.appointments
  for all using (auth.uid() = user_id);
create policy "Users manage own subscriptions" on public.subscriptions
  for all using (auth.uid() = user_id);
create policy "Users manage own knowledge" on public.knowledge
  for all using (auth.uid() = user_id);
