create table if not exists public.referral_clicks (
  id bigint generated by default as identity primary key,
  assistant_id bigint not null references public.assistants(id) on delete cascade,
  referrer text,
  page_url text,
  ip_address text,
  user_agent text,
  created_at timestamptz default now()
);

alter table public.referral_clicks enable row level security;

create policy "Users view own referral clicks" on public.referral_clicks
  for select using (exists (
    select 1 from public.assistants a where a.id = referral_clicks.assistant_id and a.user_id = auth.uid()
  ));

create policy "Allow insert referral clicks" on public.referral_clicks
  for insert with check (true);
