create table if not exists public.marketplace_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text,
  default_config jsonb default '{}'::jsonb,
  is_published boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.marketplace_templates enable row level security;

create policy "Anyone can view published templates" on public.marketplace_templates
  for select using (is_published = true);

insert into public.marketplace_templates (name, description, category, default_config) values
  ('Customer Support Agent', 'Handles common customer inquiries, tickets, and FAQs.', 'Support', '{"welcomeMessage": "Hi! How can I help you today?", "personality": "friendly"}'),
  ('Sales Representative', 'Qualifies leads, schedules demos, and follows up with prospects.', 'Sales', '{"welcomeMessage": "Hi! Interested in learning more?", "personality": "professional"}'),
  ('Appointment Scheduler', 'Books and manages appointments, sends reminders.', 'Productivity', '{"welcomeMessage": "Let me help you schedule an appointment.", "personality": "efficient"}'),
  ('FAQ Bot', 'Answers frequently asked questions from your knowledge base.', 'Support', '{"welcomeMessage": "Ask me anything about our services.", "personality": "helpful"}'),
  ('Lead Capture Agent', 'Engages visitors and captures lead information.', 'Sales', '{"welcomeMessage": "Hi! Want to stay in touch?", "personality": "engaging"}')
on conflict do nothing;
